### ISSUE TITLE
Overspend Error

### ISSUE THREAD

**Issue by Arch222** [ejbaran/algorand-tutorials-python#3]
I am getting an over-spend error even though I have 20 test Algos when I try to create the asset. I am using the Sandbox node with the typical conventions. Could someone help me with this?

**Comment by ejbaran** [comment]
Is your node fully caught up? Run `./sandbox goal node status` and check the block against a block explorer like algoexplorer.io or goalseeker.

Can you provide more info about which commands you're running?

**Comment by Arch222** [comment]
Thanks for the quick response! I checked my node; it has a lot of catching up to do( it is only on round 3370). That probably is the issue. Also, does that mean I need to run Sandbox Up testnet to run the node on testnet in order for it to work? I was currently running the Sandbox on the default private network. As per the commands, the overspending error came up when I ran create(creator_passphrase) in the Python3 Terminal.

**Comment by ejbaran** [comment]
Yes that's likely it! And yes you should use `./sandbox up testnet`. You could run this tutorial on a private network too, but might be easiest to start with TestNet so you can use the TestNet Faucet for funding.

**Comment by Arch222** [comment]
Thank you so much. I guess I have a while to wait while my node catches up but I am sure that the code itself runs fine.

**Comment by Arch222** [comment]
It worked! Nice thing to know for future projects. Closing the issue(which was not really an issue in the first place).

**Comment by ejbaran** [comment]
Great to hear it worked!
