### ISSUE TITLE
Transfer Error: add_network_params is not defined.

### ISSUE THREAD

**Issue by Bhaney44** [ejbaran/algorand-tutorials-python#4]
I'm working through the last steps in the [Dog Coin Tutorial](https://developer.algorand.org/tutorials/create-laylacoin/#5-read-the-laylacoin-balance). I successfully completed steps `4. Opt-In to Receive LaylaCoin` and `5. Read the LaylaCoin Balance` and am now working on `6. Transfer LaylaCoin to the Receiver Account`. Specifically, I am running the following lines of code.

```
## 6. Transfer LaylaCoin to the Receiver Account
from config import asset_id, creator_passphrase
from main import transfer
transfer(creator_passphrase)
```

I am receiving the following error.

```
    transfer(creator_passphrase)
  File "/Users/brianhaney/node/algorand-tutorials-python/create-laylacoin/main.py", line 99, in transfer
    data = add_network_params(transfer_data, client)
NameError: name 'add_network_params' is not defined
```

The error is coming from `line 99` of the `main.py` file, which is following line.

`data = add_network_params(transfer_data, client)`

I checked the main.py file and did not see the `add_network_params` function defined. I'm wondering what I am missing. One possibility is the problem is the arguments, either `transfer_data` or `client`. Another possibility is that I need to define the function, however I am not sure where to begin. A final possibility is that I just missed something obvious or expressly in the tutorial. 

I am going to re-read the tutorial and make sure I didn't miss anything. Then, I will continue searching through the code and problem solving. Any advice or suggestions would be greatly appreciated, thanks!

**Comment by ejbaran** [comment]
Good catch! I didn't update that code on the dev portal tutorial. Just updated it now too:

```
from algosdk.future.transaction import AssetTransferTxn

def transfer(passphrase=None):
    """
    Creates an unsigned transfer transaction for the specified asset id, to the 
    specified address, for the specified amount.
    """
    amount = 6000
    params = client.suggested_params()
    txn = AssetTransferTxn(sender=creator_address, sp=params, receiver=receiver_address, amt=amount, index=asset_id)
    if passphrase:
        txinfo = sign_and_send(txn, passphrase, client)
        formatted_amount = balance_formatter(amount, asset_id, client)
        print("Transferred {} from {} to {}".format(formatted_amount, 
            creator_address, receiver_address))
        print("Transaction ID Confirmation: {}".format(txinfo.get("tx")))
    else:
        write_to_file([txns], "transfer.txn")
```

During the v2 SDK migration, they added a `suggested_params` method that you give as an argument to a transaction constructor, which does all the work that `add_network_params` had to do before.

**Comment by Bhaney44** [comment]
Great - thanks @ejbaran ! I switched the new `transfer` function and it worked perfectly, [TXID](https://testnet.algoexplorer.io/tx/O3KPQIHOG7A2QXN2RPPD573QGXHQTZKXHADENKMJM4I2PKMXQHHA).
